parserOptions:
  ecmaVersion: 2021
  sourceType: module

extends:
  - alloy
  - alloy/typescript
  - alloy/react
  - plugin:import/recommended
  - plugin:import/typescript

env:
  browser: true
  jest: true

plugins:
  - '@typescript-eslint'
  - promise
  - '@emotion'

rules:
  import/no-unresolved: off
  react/no-unknown-property:
    - error
    - ignore:
        - css
  max-nested-callbacks: off
  max-params: off

settings:
  import/resolver:
    alias:
      map:
        - ['@/', ./src/]
      extensions:
        - .ts
        - .tsx
  react:
    version: detect
